# Generated by Django 5.2.12 on 2026-03-09 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=16)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=64)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('physician_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('display_name', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('display_name', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Signatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signatory_type', models.CharField(choices=[('medtech', 'Medical Technologist'), ('pathologist', 'Pathologist')], max_length=32)),
                ('display_name', models.CharField(max_length=255)),
                ('license_no', models.CharField(blank=True, max_length=128)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['signatory_type', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_no', models.CharField(max_length=64, unique=True)),
                ('case_number', models.CharField(blank=True, max_length=64)),
                ('patient_name_snapshot', models.CharField(max_length=255)),
                ('age_snapshot_text', models.CharField(blank=True, max_length=64)),
                ('sex_snapshot', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=16)),
                ('request_datetime', models.DateTimeField()),
                ('physician_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('room_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lab_requests', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests', to='core.patient')),
                ('physician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests', to='core.physician')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests', to='core.room')),
            ],
            options={
                'ordering': ['-request_datetime', '-id'],
                'indexes': [models.Index(fields=['request_no'], name='core_labreq_request_b5785b_idx'), models.Index(fields=['case_number'], name='core_labreq_case_nu_9891c3_idx'), models.Index(fields=['request_datetime'], name='core_labreq_request_3fea05_idx'), models.Index(fields=['status'], name='core_labreq_status_c633bf_idx')],
            },
        ),
    ]
