# Generated by Django 5.2.12 on 2026-03-10 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('contact_numbers', models.CharField(blank=True, max_length=255)),
                ('report_header_image', models.ImageField(blank=True, null=True, upload_to='facility_branding/')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['organization__legal_name', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('legal_name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['legal_name'],
            },
        ),
        migrations.AddField(
            model_name='labrequest',
            name='facility_address_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='facility_contact_numbers_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='facility_header_image_snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='request_branding/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='facility_name_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='organization_name_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests', to='core.facility'),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['facility'], name='core_labreq_facilit_daeb02_idx'),
        ),
        migrations.AddField(
            model_name='facility',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='core.organization'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.UniqueConstraint(fields=('organization', 'display_name'), name='uq_facility_name_per_organization'),
        ),
    ]
