# Generated by Django 5.2.12 on 2026-03-09 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_code', models.SlugField(max_length=64, unique=True)),
                ('exam_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['exam_name'],
            },
        ),
        migrations.CreateModel(
            name='ExamDefinitionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField()),
                ('version_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('source_type', models.CharField(blank=True, max_length=32)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('change_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='exams.examdefinition')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_exam_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_key', models.SlugField(max_length=128)),
                ('field_label', models.CharField(max_length=255)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('select', 'Select'), ('date', 'Date'), ('datetime', 'Datetime'), ('boolean', 'Boolean'), ('attachment', 'Attachment'), ('display_note', 'Display Note'), ('grouped_measurement', 'Grouped Measurement')], max_length=32)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('int', 'Integer'), ('decimal', 'Decimal'), ('date', 'Date'), ('datetime', 'Datetime'), ('boolean', 'Boolean'), ('json', 'JSON')], max_length=32)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('required', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('help_text', models.TextField(blank=True)),
                ('placeholder_text', models.CharField(blank=True, max_length=255)),
                ('reference_text', models.CharField(blank=True, max_length=255)),
                ('supports_attachment', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('exam_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='exams.examdefinitionversion')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamFieldSelectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_value', models.CharField(max_length=255)),
                ('option_label', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select_options', to='exams.examfield')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_key', models.SlugField(max_length=128)),
                ('option_label', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('exam_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.examdefinitionversion')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamFieldReferenceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sex_scope', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=16)),
                ('range_type', models.CharField(max_length=32)),
                ('min_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('max_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('reference_text', models.CharField(blank=True, max_length=255)),
                ('abnormal_rule', models.CharField(blank=True, max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='exams.examfield')),
                ('option_scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_ranges', to='exams.examoption')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamRenderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('layout_type', models.CharField(choices=[('label_value_list', 'Label Value List'), ('result_table', 'Result Table'), ('sectioned_report', 'Sectioned Report'), ('grouped_measurements', 'Grouped Measurements')], max_length=32)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('exam_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='render_profile', to='exams.examdefinitionversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_type', models.CharField(choices=[('visibility', 'Visibility'), ('requirement', 'Requirement'), ('range_selection', 'Range Selection'), ('abnormal_flag', 'Abnormal Flag'), ('validation', 'Validation')], max_length=32)),
                ('target_type', models.CharField(max_length=32)),
                ('target_id', models.PositiveIntegerField()),
                ('condition_json', models.JSONField(blank=True, default=dict)),
                ('effect_json', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('exam_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='exams.examdefinitionversion')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_key', models.SlugField(max_length=128)),
                ('section_label', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('exam_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exams.examdefinitionversion')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='examfield',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='exams.examsection'),
        ),
        migrations.AddIndex(
            model_name='examdefinitionversion',
            index=models.Index(fields=['version_status'], name='exams_examd_version_2c60b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='examdefinitionversion',
            constraint=models.UniqueConstraint(fields=('exam_definition', 'version_no'), name='uq_exam_version_number'),
        ),
        migrations.AddConstraint(
            model_name='examoption',
            constraint=models.UniqueConstraint(fields=('exam_version', 'option_key'), name='uq_exam_option_key'),
        ),
        migrations.AddConstraint(
            model_name='examsection',
            constraint=models.UniqueConstraint(fields=('exam_version', 'section_key'), name='uq_exam_section_key'),
        ),
        migrations.AddIndex(
            model_name='examfield',
            index=models.Index(fields=['exam_version', 'field_key'], name='exams_examf_exam_ve_510189_idx'),
        ),
        migrations.AddIndex(
            model_name='examfield',
            index=models.Index(fields=['input_type'], name='exams_examf_input_t_0e0e91_idx'),
        ),
        migrations.AddConstraint(
            model_name='examfield',
            constraint=models.UniqueConstraint(fields=('exam_version', 'field_key'), name='uq_exam_field_key'),
        ),
    ]
