# Generated by Django 5.2.12 on 2026-03-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examfield',
            name='config_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
