# Generated by Django 5.2.12 on 2026-03-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('system_owner', 'System Owner'), ('admin', 'Admin'), ('encoder', 'Encoder'), ('viewer', 'Viewer')], default='encoder', max_length=32),
        ),
    ]
